#ifndef PQS_META_DETAIL_MACRO_CAT_HPP_INCLUDED
#define PQS_META_DETAIL_MACRO_CAT_HPP_INCLUDED

#define PQS_MACRO_CAT(A,B) PQS_MACRO_CAT_IMPL(A,B)
#define PQS_MACRO_CAT_IMPL(A,B) PQS_MACRO_CAT_IMPL2(A,B)
#define PQS_MACRO_CAT_IMPL2(A,B) A##B 

#endif
